### PR TITLE
rename libparallelproj and build v1.3.4

### PR DESCRIPTION
**Pull request by gschramm**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gschramm** [comment]
conda-forge-admin, please rerender

**Comment by gschramm** [comment]
conda-forge-admin, please rerender

**Comment by gschramm** [comment]
@h-vetinari I managed to make some progress (but still not there yet ;).
Here is what I did:
1. I build v1.3.3 and renamed the first output to `libparallelproj`. Cross-builds were still breaking, but after removing `noarch:python` everything went well (2nd output called `parallelprojpy`)
2. I released v1.3.4 where I renamed the python binding to `parallelproj` and also adapted the recipe accordingly (latest build). However, now all build are breaking when build the python package (running build-python.sh) with the error: `/home/conda/feedstock_root/build_artifacts/parallelproj_1682091537772/work/build-python.sh: line 4: /home/conda/feedstock_root/build_artifacts/parallelproj_1682091537772/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/bin/python: No such file or directory`. Any idea why that happens (and did not happen before)? Is python missing as build req. (why wasn't it before)?

**Comment by gschramm** [comment]
@h-vetinari changing the global package name to `libparallelproj` fixed the problems (1st output has name `libparallelproj`, 2nd `parallelproj`) :) Not sure however why it works this way, but not the other. Before merging, 
could you check if the `run_constrained` is correct?

**Comment by h-vetinari** [comment]
> I am also confused by the difference between `package: name:` and `output:name`. `tomopy` which also has a `lib` output and an python output (tomopy) uses `libtomo` (the lib name) as package name. Right now (as before), I am using `parallelproj` (also the name of the python output) as package name.

The "package name" (really the feedstock) and the output names may not coincide. Bad things can happen if so (tests not run correctly, etc.), and it should always be avoided. Unfortunately conda doesn't do a good job about warning about this footgun. So please rename the "package" to `parallelproj-split` and add a `feedstock-name: parallelproj` under `extras:`

**Comment by h-vetinari** [comment]
The [CI](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=694542&view=results) for the last commit _looks_ green, but the fact that there's several `BUILD START:` is highly suspect, and the final outputs at the end look like parallelproj has no python dependence, which is also wrong.

**Comment by h-vetinari** [comment]
Now that you've removed the `noarch: python`, you need to also do:
```diff
-        - python >=3.6,<4
+        - python
```
and rerender

**Comment by gschramm** [comment]
> Now that you've removed the `noarch: python`, you need to also do:
> 
> ```diff
> -        - python >=3.6,<4
> +        - python
> ```
> 
> and rerender

Thanks again for all the feedback! Should `python` be a `host` or `run` dependence for the 2nd output?
I'd say `run`, but not 100% sure.

**Comment by gschramm** [comment]
conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
> Should `python` be a `host` or `run` dependence for the 2nd output?
> I'd say `run`, but not 100% sure.

Host is correct 👌



> Btw: sorry for all the work that I am causing.

No worries. You ran into some tricky problems. I think it should still be possible to make this noarch, but there's something going wrong with the python runexports in cross-compilation (my current suspicion). In any case, better to unblock this now, even if we build a few more versions...

**Comment by h-vetinari** [comment]
You forgot the `@` to summon the bot

@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
Looks good now AFAICT 👍

**Comment by gschramm** [comment]
> Looks good now AFAICT 👍

Thanks again! I'll merge the PR now :)

**Pull request merged**
